In [1]:
import numpy

In [2]:
x=numpy.array([11,22,33,44])

In [3]:
x

array([11, 22, 33, 44])

In [4]:
print(x)

[11 22 33 44]


In [5]:
import numpy as np

In [6]:
y=np.array([100,200,300])

In [7]:
print(y)

[100 200 300]


In [8]:
print(np.__version__)

1.20.1


In [10]:
#using tuple

In [11]:
z=np.array((50,60,70,80))

In [12]:
print(z)

[50 60 70 80]


In [13]:
#two dimensional array

In [15]:
x1=np.array([[1,2,3],[5,6,7]])

In [16]:
print(x1)

[[1 2 3]
 [5 6 7]]


In [18]:
y1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
print(y1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#zero dimension

In [21]:
z1=np.array(56)

In [22]:
print(z1)

56


In [23]:
#to find dimension of array 

In [25]:
print(z1.ndim)

0


In [26]:
print(y1.ndim)

2


In [27]:
print(x1.ndim)

2


In [28]:
print(z.ndim)

1


In [29]:
#three dimensional array

In [30]:
q1=np.array([[[1,2,3],[5,6,7],[10,20,30],[50,60,70]]])

In [31]:
print(q1)

[[[ 1  2  3]
  [ 5  6  7]
  [10 20 30]
  [50 60 70]]]


In [32]:
print(q1.ndim)

3


In [33]:
#array index

In [17]:
#one dimensional array index

In [34]:
print(x)

[11 22 33 44]


In [35]:
print(x[2])

33


In [ ]:
#two dimensional array index

In [36]:
print(x1)

[[1 2 3]
 [5 6 7]]


In [37]:
print(x1[0,2])

3


In [38]:
print(x1[1,1])

6


In [39]:
#three dimensional array index

In [42]:
w=np.array([[[12,13,14],[15,16,17]],[[10,11,12],[9,8,7]]])

In [44]:
print(w)

[[[12 13 14]
  [15 16 17]]

 [[10 11 12]
  [ 9  8  7]]]


In [45]:
print(w[0,1,2])

17


In [46]:
print(w[1,1,1,])

8
